version: '3'

services:
  envoy:
    image: envoyproxy/envoy:v1.26.1
    volumes:
      - ./envoy-demo.yaml:/etc/envoy/envoy.yaml
      - ./Protos/greet.pb:/etc/envoy/greet.pb
    expose:
      - "8080"
      - "10000"
      - "9901"
      - "8500"
    ports:
      - 10000:10000
      - 8080:8080
      - 9901:9901
      - 8500:8500

  demo_greeter:
    image: grpcgreeter:latest
    ports:
     - "50333:80"